apiVersion: v1
kind: PersistentVolume
metadata:
  name: sobel-images-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /home/valentin/Proyectos/TP3_SDyPP/hit1/img
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sobel-images-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sobel-logs-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /home/valentin/Proyectos/TP3_SDyPP/hit1/etapa4-k3s/logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sobel-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 500Mi
