services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
    profiles:
      - producer
    volumes:
      - ./logs:/app/logs
