---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: default
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z rabbitmq 5672; do
                echo "Esperando a RabbitMQ...";
                sleep 3;
              done;
              echo "RabbitMQ disponible."
      containers:
        - name: consumer
          image: consumer:latest   # Reemplazar con tu imagen publicada en un registry
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_URL
              value: "amqp://$(RABBITMQ_USER):$(RABBITMQ_PASS)@rabbitmq:5672"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASS
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
